-- AlterTable
ALTER TABLE "Category" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "MemoCard" ALTER COLUMN "lastPracticeTimestamp" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "createdAtTimestamp" SET DEFAULT CURRENT_TIMESTAMP;
